/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "EIP3074Protection",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP3074Protection__factory>;
    getContractFactory(
      name: "EIP3074ProtectionTest",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.EIP3074ProtectionTest__factory>;
    getContractFactory(
      name: "OnlyEOAs",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.OnlyEOAs__factory>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
  }
}
