/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface OnlyEOAsInterface extends ethers.utils.Interface {
  functions: {
    "doSomething()": FunctionFragment;
    "doSomethingElse()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "doSomething",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "doSomethingElse",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "doSomething",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "doSomethingElse",
    data: BytesLike
  ): Result;

  events: {
    "GasInfo(uint256,uint256)": EventFragment;
    "Success(bool)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "GasInfo"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Success"): EventFragment;
}

export class OnlyEOAs extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: OnlyEOAsInterface;

  functions: {
    doSomething(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    doSomethingElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  doSomething(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  doSomethingElse(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    doSomething(overrides?: CallOverrides): Promise<void>;

    doSomethingElse(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    GasInfo(
      txgas?: null,
      gaslimit?: null
    ): TypedEventFilter<
      [BigNumber, BigNumber],
      { txgas: BigNumber; gaslimit: BigNumber }
    >;

    Success(val?: null): TypedEventFilter<[boolean], { val: boolean }>;
  };

  estimateGas: {
    doSomething(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    doSomethingElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    doSomething(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    doSomethingElse(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
